FROM gliderlabs/alpine:3.1
ENTRYPOINT ["/bin/resolvable"]

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/mgood/resolvable
RUN cd /go/src/github.com/mgood/resolvable \
	&& go get \
	&& go build -ldflags "-X main.Version dev" -o /bin/resolvable
